# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_6UVaFDV5soepzozBULIl2QHlfGI1_F0
"""



import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image
import gc  # Garbage collector to free up RAM

# --- Page Config ---
st.set_page_config(page_title="CyberFusion-AI", page_icon="🛡️")

# --- Optimized Model Loading ---
@st.cache_resource
def load_my_model():
    # Loading the .h5 model you uploaded to your repo
    model = tf.keras.models.load_model("fake_face_model.h5")
    return model

# --- Main UI ---
st.title("🛡️ CyberFusion-AI")
st.markdown("### Public Release: Deepfake Detection")

uploaded_file = st.file_uploader("Upload a face to analyze", type=["jpg", "png", "jpeg"])

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption="Uploaded Image", use_container_width=True)
    
    if st.button("Start Analysis"):
        with st.spinner("Processing pixels..."):
            # 1. Load Model
            model = load_my_model()
            
            # 2. Preprocess
            img = image.resize((128, 128))
            img_array = tf.keras.preprocessing.image.img_to_array(img)
            img_array = img_array / 255.0  # Normalization
            img_array = np.expand_dims(img_array, axis=0)
            
            # 3. Predict
            prediction = model.predict(img_array)
            score = prediction[0][0]
            
            # 4. Show Result
            if score > 0.5:
                st.error(f"**Result: FAKE** (Confidence: {score:.2%})")
            else:
                st.success(f"**Result: REAL** (Confidence: {(1-score):.2%})")
            
            # 5. Cleanup memory
            del img_array
            gc.collect()

st.divider()
st.caption("CyberFusion-AI Project | Built with Python & TensorFlow")
