# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_6UVaFDV5soepzozBULIl2QHlfGI1_F0
"""


import streamlit as st
import numpy as np
from tensorflow.keras.models import load_model
from PIL import Image
import requests
import os

# Model link (GitHub release)
MODEL_URL = "https://github.com/shrashttomar-design/Fake-Face-Detection/releases/download/v1.0.0/fake_face_model.keras"
MODEL_PATH = "fake_face_model.keras"

@st.cache_resource
def load_my_model():
    if not os.path.exists(MODEL_PATH):
        with open(MODEL_PATH, "wb") as f:
            f.write(requests.get(MODEL_URL).content)
    return load_model(MODEL_PATH)

model = load_my_model()

st.set_page_config(page_title="Fake Face Detection", layout="centered")

st.title("🕵️ Fake Face Detection System")
st.write("Upload an image to check whether it is REAL or FAKE")

uploaded_file = st.file_uploader("Upload Image", type=["jpg","png","jpeg"])

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    image = image.resize((128,128))

    st.image(image, caption="Uploaded Image", use_column_width=True)

    img = np.array(image) / 255.0
    img = np.reshape(img, (1,128,128,3))

    prediction = model.predict(img)
    confidence = float(prediction[0][0])

    st.subheader("Result:")

    if confidence > 0.5:
        st.error(f"❌ FAKE FACE ({confidence*100:.2f}%)")
    else:
        st.success(f"✅ REAL FACE ({(1-confidence)*100:.2f}%)")
st.write("⏳ Loading model... please wait")

model = load_my_model()

st.write("✅ Model loaded")
