# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_6UVaFDV5soepzozBULIl2QHlfGI1_F0
"""


import streamlit as st
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model
from PIL import Image
import requests
import os

# 1. Configuration - Move to the VERY top
st.set_page_config(page_title="Fake Face Detection", layout="centered")

# Model info
MODEL_URL = "https://github.com/shrashttomar-design/Fake-Face-Detection/releases/download/v1.0.0/fake_face_model.keras"
MODEL_PATH = "fake_face_model.keras"

@st.cache_resource
def load_my_model():
    if not os.path.exists(MODEL_PATH):
        with st.spinner("Downloading model from GitHub... this may take a moment."):
            response = requests.get(MODEL_URL, stream=True)
            if response.status_code == 200:
                with open(MODEL_PATH, "wb") as f:
                    f.write(response.content)
            else:
                st.error("Failed to download model. Check the MODEL_URL.")
                return None
    return load_model(MODEL_PATH)

# Load the model once
model = load_my_model()

st.title("🕵️ Fake Face Detection System")
st.write("Upload an image to check whether it is **REAL** or **FAKE**")

uploaded_file = st.file_uploader("Choose an image...", type=["jpg","png","jpeg"])

if uploaded_file is not None and model is not None:
    # Display image
    image = Image.open(uploaded_file).convert('RGB') # Ensure 3 channels
    st.image(image, caption="Uploaded Image", use_container_width=True)
    
    # Preprocessing
    with st.spinner("Analyzing..."):
        img_resized = image.resize((128, 128))
        img_array = np.array(img_resized) / 255.0
        img_reshape = np.expand_dims(img_array, axis=0) # Better than np.reshape for clarity

        # Prediction
        prediction = model.predict(img_reshape)
        confidence = float(prediction[0][0])

    st.divider()
    st.subheader("Result:")

    if confidence > 0.5:
        st.error(f"❌ **FAKE FACE** (Confidence: {confidence*100:.2f}%)")
    else:
        st.success(f"✅ **REAL FACE** (Confidence: {(1-confidence)*100:.2f}%)")

elif model is None:
    st.warning("Model could not be loaded. Please check the logs.")
